name: CD

on:
  push:
    branches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@v2
    -name: Deploy to AWS
     run: |
      aws ecs update-service --cluster <cluster-name> --service
<service-name> --force-new-deployment
